# Generated by Django 5.2.3 on 2025-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(default='Apple', max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('display_size', models.CharField(max_length=20)),
                ('camera', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
